CREATE TABLE IF NOT EXISTS customer_booking_staging (
    booking_id              VARCHAR(20),
    customer_id             VARCHAR(20),
    customer_name           VARCHAR(100),
    email                   VARCHAR(100),
    loyalty_tier            VARCHAR(20),
    loyalty_points          INT,
    booking_date            DATE,
    pickup_location         VARCHAR(100),
    pickup_time             VARCHAR(20),
    drop_location           VARCHAR(100),
    drop_time               VARCHAR(20),
    pickup_hour             INT,
    pickup_slot             VARCHAR(20),
    trip_type               VARCHAR(20),
    route                   VARCHAR(100),
    booking_year            INT,
    booking_month           INT,
    email_domain            VARCHAR(50),
    loyalty_rank            INT,
    is_high_value_customer  BOOLEAN,
    points_tier             VARCHAR(20),
    car_id                  VARCHAR(20),
    model                   VARCHAR(50),
    price_per_day           DOUBLE PRECISION,
    insurance_provider      VARCHAR(50),
    insurance_coverage      VARCHAR(20),
    price_tier              VARCHAR(20),
    has_full_insurance      BOOLEAN,
    insurer_type            VARCHAR(20),
    car_segment             VARCHAR(20),
    payment_id              VARCHAR(20),
    payment_method          VARCHAR(30),
    payment_amount          DOUBLE PRECISION,
    is_digital_payment      BOOLEAN,
    amount_tier             VARCHAR(20),
    payment_count           BIGINT,
    is_split_payment        BOOLEAN
);