CREATE TABLE IF NOT EXISTS customer_booking_staging (
    booking_id          VARCHAR(20),
    customer_id         VARCHAR(20),
    customer_name       VARCHAR(100),
    email               VARCHAR(100),
    loyalty_tier        VARCHAR(20),
    loyalty_points      INT,
    booking_date        DATE,
    pickup_location     VARCHAR(100),
    pickup_time         VARCHAR(20),
    drop_location       VARCHAR(100),
    drop_time           VARCHAR(20),
    car_id              VARCHAR(20),
    model               VARCHAR(50),
    price_per_day       DOUBLE PRECISION,
    insurance_provider  VARCHAR(50),
    insurance_coverage  VARCHAR(20),
    payment_id          VARCHAR(20),
    payment_method      VARCHAR(30),
    payment_amount      DOUBLE PRECISION
);